#!/bin/bash
# /etc/init.d/tempwatcherd

### BEGIN INIT INFO
# Provides:          tempwatcher
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This service is used to measure a temperature sensor and notify a user
### END INIT INFO


case "$1" in
    start)
        echo "Starting web server"
        python web/server.py&
        echo $! > web_server.pid
        echo "Starting sensor query loop"
        python tools/query.py&
        echo $! > query.pid
        ;;
    stop)
        echo "Stopping webserver"
        kill -TERM $(cat web_server.pid)
        echo "Stopping sensor query loop"
        kill -TERM $(cat query.pid)
        ;;
    *)
        echo "Usage: /etc/init.d/tempwatcherd start|stop"
        exit 1
        ;;
esac

exit 0